export const originPayroll = [
  {
    inputs: [
      { name: "_mailbox", internalType: "address", type: "address" },
      {
        name: "_interchainGasPaymaster",
        internalType: "address",
        type: "address",
      },
      { name: "_destinationPayroll", internalType: "address", type: "address" },
      { name: "_destinationChainId", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "DestinationPayrollNotSet", type: "error" },
  { inputs: [], name: "InterchainGasPaymasterNotSet", type: "error" },
  { inputs: [], name: "InvalidAmount", type: "error" },
  { inputs: [], name: "InvalidArrayLength", type: "error" },
  { inputs: [], name: "InvalidBankAccount", type: "error" },
  { inputs: [], name: "InvalidCurrency", type: "error" },
  { inputs: [], name: "InvalidEmployee", type: "error" },
  { inputs: [], name: "MailboxNotSet", type: "error" },
  { inputs: [], name: "NotOwner", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "SameChain", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  {
    inputs: [
      {
        indexed: true,
        name: "payrollId",
        internalType: "bytes32",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "employees",
        internalType: "address[]",
        type: "address[]",
      },
      {
        indexed: false,
        name: "cryptoAmounts",
        internalType: "uint256[]",
        type: "uint256[]",
      },
      {
        indexed: false,
        name: "fiatAmounts",
        internalType: "uint256[]",
        type: "uint256[]",
      },
      {
        indexed: false,
        name: "currencies",
        internalType: "string[]",
        type: "string[]",
      },
      {
        indexed: false,
        name: "bankAccounts",
        internalType: "string[]",
        type: "string[]",
      },
    ],
    name: "PayrollBatchDetails",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "payrollId",
        internalType: "bytes32",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "totalRecipients",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "totalCryptoAmount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "totalFiatAmount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "timestamp",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "PayrollBatchSent",
    anonymous: false,
    type: "event",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "destinationChainId",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "destinationPayroll",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "emergencyWithdraw",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "messageId", internalType: "bytes32", type: "bytes32" }],
    inputs: [
      { name: "employees", internalType: "address[]", type: "address[]" },
      { name: "cryptoAmounts", internalType: "uint256[]", type: "uint256[]" },
      { name: "fiatAmounts", internalType: "uint256[]", type: "uint256[]" },
      { name: "currencies", internalType: "string[]", type: "string[]" },
      { name: "bankAccounts", internalType: "string[]", type: "string[]" },
    ],
    name: "executePayrollBatch",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [
      { name: "_mailbox", internalType: "address", type: "address" },
      {
        name: "_interchainGasPaymaster",
        internalType: "address",
        type: "address",
      },
      { name: "_destinationPayroll", internalType: "address", type: "address" },
      { name: "_destinationChainId", internalType: "uint256", type: "uint256" },
    ],
    inputs: [],
    name: "getConfig",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "interchainGasPaymaster",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "mailbox",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "owner",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_destinationPayroll", internalType: "address", type: "address" },
    ],
    name: "setDestinationPayroll",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      {
        name: "_interchainGasPaymaster",
        internalType: "address",
        type: "address",
      },
    ],
    name: "setInterchainGasPaymaster",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_mailbox", internalType: "address", type: "address" }],
    name: "setMailbox",
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
