[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Gas configuration for Core testnet
gas_price = 1000000000  # 1 gwei
gas_limit = 5000000     # 5M gas limit
priority_gas_price = 1000000000  # 1 gwei priority fee

[rpc_endpoints]
core_testnet = "https://rpc.test2.btcs.network"
etherlink_testnet = "https://node.ghostnet.etherlink.com"
arb_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base_sepolia = "https://sepolia.base.org"
op_sepolia = "https://sepolia.optimism.io"
citrea_testnet = "https://rpc.testnet.citrea.xyz"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
