[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

# Gas configuration for Core testnet
gas_price = 100000000000  # 100 gwei (network requirement)
gas_limit = 30000000    # 30M gas limit
priority_gas_price = 100000000000  # 100 gwei priority fee (network requirement)

[rpc_endpoints]
core_testnet = "https://rpc.test2.btcs.network"
etherlink_testnet = "https://node.ghostnet.etherlink.com"
arb_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base_sepolia = "https://sepolia.base.org"
op_sepolia = "https://sepolia.optimism.io"
citrea_testnet = "https://rpc.testnet.citrea.xyz"
bitlayer_testnet = "https://rpc.ankr.com/bitlayer_testnet"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
